apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-chart
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: my-chart
  template:
    metadata:
      labels:
        app.kubernetes.io/name: my-chart
    spec:
      containers:
        - name: hang
          image: jackwilsdon/hang
      terminationGracePeriodSeconds: 0
